workflows:
  android-release:
    name: MKTIA Android APK & AppBundle
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build Android App Bundle
        script: |
          cd android && ./gradlew bundleRelease --stacktrace
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk