workflows:
  android-release:
    name: MKTIA Android APK & AppBundle
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release --android-skip-build-dependency-validation
      - name: Build Android APK
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk